# Site settings
title: Alex Levy
tagline: "Mainly nonsense, sometimes useful"
email: alex@alexlevy.co.uk
description: >

baseurl: ""
url: "http://alexlevy.co.uk"
permalink: none
github_username:  alexlukelevy
linkedin_username: alex-levy-73b0552b
repository: alexlukelevy/alexlukelevy.github.io

# Build settings
markdown: kramdown
